export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const BRANDS_REQUESTED = 'BRANDS_REQUESTED';
export const BRANDS_LOADED = 'BRANDS_LOADED';
export const API_ERROR = 'API_ERROR';
export default '';
