export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const BRANDS_REQUESTED = 'BRANDS_REQUESTED';
export const BRANDS_LOADED = 'BRANDS_LOADED';
export const VEHICLES_REQUESTED = 'VEHICLES_REQUESTED';
export const VEHICLES_LOADED = 'VEHICLES_LOADED';
export const MODELS_REQUESTED = 'MODELS_REQUESTED';
export const API_ERROR = 'API_ERROR';
export default '';
